# ===================================
#  List Behavior Config
# ===================================

title: system::lang.mail_templates.menu_label
list: ~/modules/system/models/mailtemplate/columns.yaml
modelClass: System\Models\MailTemplate
recordUrl: system/mailtemplates/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true

toolbar:
    buttons: list_templates_toolbar
    search:
        prompt: backend::lang.list.search_prompt