# ===================================
#  List Behavior Config
# ===================================

title: system::lang.mail_templates.menu_label
list: ~/modules/system/models/maillayout/columns.yaml
modelClass: System\Models\MailLayout
recordUrl: system/maillayouts/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true

toolbar:
    buttons: list_layouts_toolbar
    search:
        prompt: backend::lang.list.search_prompt