# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Log

# Model Form Field configuration
form: ~/modules/system/models/requestlog/fields.yaml

# Model Class name
modelClass: System\Models\RequestLog

# Default redirect location
defaultRedirect: system/requestlogs

# Preview page
preview:
    title: Request