# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.user.group.list_title
list: ~/modules/backend/models/usergroup/columns.yaml
modelClass: Backend\Models\UserGroup
recordUrl: backend/usergroups/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 5
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
