# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.user.list_title
list: ~/modules/backend/models/user/columns.yaml
modelClass: Backend\Models\User
recordUrl: backend/users/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt