# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Log

# Model Form Field configuration
form: ~/modules/system/models/eventlog/fields.yaml

# Model Class name
modelClass: System\Models\EventLog

# Default redirect location
defaultRedirect: system/eventlogs

# Preview page
preview:
    title: Event